export enum Genre {
  acao = 'acao',
  aventura = 'aventura',
  comedia = 'comedia',
  comedia_de_acao = 'comedia_de_acao',
  comedia_de_terror = 'comedia_de_terror',
  comedia_dramatica = 'comedia_dramatica',
  comedia_romantica = 'comedia_romantica',
  danca = 'danca',
  documentario = 'documentario',
  drama = 'drama',
  espionagem = 'espionagem',
  foreste = 'foreste',
  faroeste = 'faroeste',
  fantasia = 'fantasia',
  fantasia_cientifica = 'fantasia_cientifica',
  ficcao_cientifica = 'ficcao_cientifica',
  guerra = 'guerra',
  misterio = 'misterio',
  policial = 'policial',
  romance = 'romance',
  terror = 'terror',
  thriller = 'thriller',
}
